name: Build Thunderstore ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-thunderstore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Upload Thunderstore Folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: Thunderstore
